# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='impact_score',
            field=models.FloatField(null=True),
        ),
    ]
