# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeps', '0002_auto_20160611_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
